name: test

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - '*'



env:
  GCLOUD_VERSION: 'latest'
  NODE_VERSION: '15'
  MAKEFLAGS: '-j2'

  BQ_PROJECTID: bqcartoci
  BQ_DATASET_PREFIX: ${{ github.sha }}
  POST_INTEGRATION_CLEANUP: 1

jobs:
  test-extension:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:

      - name: test
        run: echo "${{ github.event.sender.login }}"


      - name: Checkout repo
        uses: actions/checkout@v2
