name: test

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - '*'

env:
  GCLOUD_VERSION: 'latest'
  NODE_VERSION: '15'
  MAKEFLAGS: '-j2'

  BQ_PROJECTID: bqcartoci
  BQ_DATASET_PREFIX: ${{ github.sha }}
  POST_INTEGRATION_CLEANUP: 1

jobs:
  test-extension:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:

      - name: get list of carto team members
        uses: octokit/request-action@v2.x
        id: get_carto_team_members
        with:
          route: GET https://api.github.com/orgs/CartoDB/teams/carto-team-all/members
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: check event sender is carto member
        run: |
          echo ${{ steps.get_latest_release.outputs.data }}
          echo ${{ steps.get_latest_release.outputs.data }} | grep '"login":' | grep -w ibrahimmenem
        
      - name: Checkout repo
        uses: actions/checkout@v2
