name: teste

on:
#  pull_request_review:
#    types: [submitted]
  push:
    branches:
      - '*'
  pull_request_target:
    types: [labeled]

env:
  GCLOUD_VERSION: 'latest'
  NODE_VERSION: '15'
  MAKEFLAGS: '-j2'

  BQ_PROJECTID: bqcartoci
  BQ_DATASET_PREFIX: ${{ github.sha }}
  POST_INTEGRATION_CLEANUP: 1

jobs:
  test-extension:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:

      - name: user
        run: echo "${{ github.event.sender.login }}"

      - name: event
        run: echo "${{ ToJSON(github.event) }}"
      - name: ls before
        run: ls



      - name: Checkout repo
        uses: actions/checkout@v2

      - name: checkout fork HEAD
        run: git checkout ${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request_target'

      - name: ls after
        run: ls
