name: test

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - '*'
  workflow_dispatch:
  pull_request_target:
    types: [labeled]

env:
  GCLOUD_VERSION: 'latest'
  NODE_VERSION: '15'
  MAKEFLAGS: '-j2'

  BQ_PROJECTID: bqcartoci
  BQ_DATASET_PREFIX: ${{ github.sha }}
  POST_INTEGRATION_CLEANUP: 1

jobs:
  test-extension:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:

      - name: user
        run: echo "${{ github.event.sender.login }}"
      - name: action
        run: echo "${{ github.action }}"
      - name: event
        run: echo "${{ github.event }}"

#      - name: fail if trigger is push and user is not org user, non-carto user should go via pull request
#        uses: octokit/request-action@v2.x
#        with:
#          route: GET /orgs/CartoDB/members/${{ github.event.sender.login }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if: github.event_name == 'push'
#
#      - name: fail if trigger is pull_request_review and user is not org user, non-carto user should go via pull request
#        uses: octokit/request-action@v2.x
#        with:
#          route: GET /orgs/CartoDB/members/${{ github.event.review.user.login }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if: github.event_name == 'pull_request_review'

      - name: Checkout repo
        uses: actions/checkout@v2
